package io.github.jabhijeet.schema.json;

import io.github.jabhijeet.schema.io.AvroIO;
import io.github.jabhijeet.schema.io.ParquetIO;
import org.apache.avro.Schema;
import org.apache.avro.generic.GenericRecord;

import java.io.InputStream;
import java.util.List;
import java.util.Objects;

/**
 * One-call facade for converting JSON documents into Avro or Parquet bytes.
 *
 * <p>Combines {@link JsonToGenericRecordConverter} (JSON → {@link GenericRecord}) with
 * {@link AvroIO} / {@link ParquetIO} (GenericRecord → binary).  All operations
 * are fully in‑memory — no filesystem, no {@code HADOOP_HOME} required.
 *
 * <p>A single shared {@link JsonToGenericRecordConverter} instance is used internally;
 * it is stateless and thread‑safe. All methods are static and can be safely
 * called from multiple threads concurrently.
 *
 * <h2>Typical workflow</h2>
 * <ol>
 *   <li>Generate an Avro schema from a POJO class using {@link io.github.jabhijeet.schema.PojoSchemaGenerator}.</li>
 *   <li>Convert JSON strings (or streams) to Avro or Parquet bytes via {@link #toAvroBytes(String, Schema)},
 *       {@link #toParquetBytes(String, Schema)} and their batch variants.</li>
 *   <li>Read back bytes to JSON strings using {@link #fromAvroBytes(byte[])} or
 *       {@link #fromParquetBytes(byte[])}.</li>
 * </ol>
 *
 * <h2>Usage examples</h2>
 *
 * <h3>Basic single‑record conversion</h3>
 * <pre>{@code
 * // 1. Obtain an Avro schema (from a POJO or manually)
 * Schema schema = PojoSchemaGenerator.toAvro(OrderPojo.class);
 *
 * // 2. Convert a JSON document to Avro bytes
 * String orderJson = "{\"orderId\": \"123\", \"amount\": 99.99}";
 * byte[] avroBytes = JsonIO.toAvroBytes(orderJson, schema);
 *
 * // 3. Convert the same JSON to Parquet bytes (Snappy compression by default)
 * byte[] parquetBytes = JsonIO.toParquetBytes(orderJson, schema);
 *
 * // 4. Read the Avro bytes back into JSON strings
 * List<String> jsonStrings = JsonIO.fromAvroBytes(avroBytes);
 * }</pre>
 *
 * <h3>Batch conversion (JSON array)</h3>
 * <pre>{@code
 * String ordersJson = "[{...}, {...}, {...}]";
 * byte[] avroAll = JsonIO.toAvroBytesAll(ordersJson, schema);
 * byte[] parquetAll = JsonIO.toParquetBytesAll(ordersJson, schema);
 * }</pre>
 *
 * <h3>Working with InputStreams</h3>
 * <pre>{@code
 * try (InputStream in = new FileInputStream("order.json")) {
 *     byte[] avro = JsonIO.toAvroBytes(in, schema);
 *     // process bytes...
 * }
 * }</pre>
 *
 * <h3>Flattened schemas</h3>
 * <p>When the Avro schema carries the {@code pojoSchemaFlattened=true} property
 * (generated by {@link io.github.jabhijeet.schema.PojoSchemaGenerator} with
 * {@link io.github.jabhijeet.schema.SchemaOptions#flatten()}), the converter
 * automatically reconstructs nested JSON from flat field names.
 *
 * <pre>{@code
 * // POJO with nested fields, flattened schema
 * Schema flatSchema = PojoSchemaGenerator.toAvro(CustomerPojo.class,
 *     SchemaOptions.builder().flatten(true).build());
 *
 * // JSON with flat keys
 * String flatJson = "{\"customer.name\": \"Alice\", \"customer.address.city\": \"NYC\"}";
 * byte[] avro = JsonIO.toAvroBytes(flatJson, flatSchema);
 *
 * // Reading back yields nested JSON
 * List<String> nestedJson = JsonIO.fromAvroBytes(avro);
 * }</pre>
 *
 * <h3>Parquet to JSON conversion</h3>
 * <p>There is no separate {@code ParquetToJsonConverter} class. Parquet bytes are
 * first read into {@link GenericRecord}s via {@link io.github.jabhijeet.schema.io.ParquetIO#readAll(byte[])},
 * then each record is converted to JSON using the shared {@link GenericRecordToJsonConverter}.
 * The {@link #fromParquetBytes(byte[])} method provides a convenient one‑call
 * facade for this operation.
 *
 * <pre>{@code
 * byte[] parquetBytes = ...;
 * List<String> jsonStrings = JsonIO.fromParquetBytes(parquetBytes);
 * }</pre>
 *
 * <h3>Error handling</h3>
 * <p>All conversion methods throw {@link JsonConversionException} if the input
 * JSON does not match the schema (missing required fields, type mismatches, etc.).
 * The exception includes a detailed message pointing to the offending field.
 *
 * @see io.github.jabhijeet.schema.PojoSchemaGenerator
 * @see io.github.jabhijeet.schema.json.JsonToGenericRecordConverter
 * @see io.github.jabhijeet.schema.json.GenericRecordToJsonConverter
 * @see io.github.jabhijeet.schema.io.AvroIO
 * @see io.github.jabhijeet.schema.io.ParquetIO
 */
public final class JsonIO {

    private static final JsonToGenericRecordConverter CONVERTER = new JsonToGenericRecordConverter();
    private static final GenericRecordToJsonConverter TO_JSON   = new GenericRecordToJsonConverter();

    private JsonIO() {
        // utility
    }

    // ---------------------------------------------------------------- JSON â†’ record

    /**
     * Parses {@code json} into a {@link GenericRecord} that conforms to {@code schema}.
     *
     * @throws JsonConversionException if the JSON does not match the schema
     */
    public static GenericRecord toRecord(String json, Schema schema) {
        Objects.requireNonNull(json, "json");
        Objects.requireNonNull(schema, "schema");
        return CONVERTER.convert(json, schema);
    }

    /**
     * Parses {@code json} into a {@link GenericRecord} that conforms to {@code schema},
     * rejecting input longer than {@code maxJsonLength} characters.
     *
     * <p>This method provides a memory‑safety guard against accidentally
     * processing extremely large JSON strings that could exhaust heap memory.
     * The length check is performed before any parsing or tree construction.
     *
     * @param json JSON string to parse
     * @param schema Avro record schema
     * @param maxJsonLength maximum allowed length of the JSON string (in characters)
     * @return converted record
     * @throws JsonConversionException if the JSON exceeds {@code maxJsonLength}
     * @since 1.0.0
     */
    public static GenericRecord toRecord(String json, Schema schema, int maxJsonLength) {
        Objects.requireNonNull(json, "json");
        Objects.requireNonNull(schema, "schema");
        return CONVERTER.convert(json, schema, maxJsonLength);
    }

    /**
     * Reads a JSON document from {@code in} and converts it to a {@link GenericRecord}.
     * Closes the stream before returning.
     *
     * @throws JsonConversionException if the JSON does not match the schema
     */
    public static GenericRecord toRecord(InputStream in, Schema schema) {
        Objects.requireNonNull(in, "in");
        Objects.requireNonNull(schema, "schema");
        return CONVERTER.convert(in, schema);
    }

    /**
     * Converts a JSON array (or single object) to a list of {@link GenericRecord}s.
     *
     * @throws JsonConversionException if any element does not match the schema
     */
    public static List<GenericRecord> toRecords(String json, Schema schema) {
        Objects.requireNonNull(json, "json");
        Objects.requireNonNull(schema, "schema");
        return CONVERTER.convertAll(json, schema);
    }

    /**
     * Converts a JSON array (or single object) to a list of {@link GenericRecord}s,
     * rejecting input longer than {@code maxJsonLength} characters.
     *
     * <p>This method provides a memory‑safety guard against accidentally
     * processing extremely large JSON strings that could exhaust heap memory.
     * The length check is performed before any parsing or tree construction.
     *
     * @param json JSON string to parse
     * @param schema Avro record schema
     * @param maxJsonLength maximum allowed length of the JSON string (in characters)
     * @return list of converted records
     * @throws JsonConversionException if the JSON exceeds {@code maxJsonLength}
     * @since 1.0.0
     */
    public static List<GenericRecord> toRecords(String json, Schema schema, int maxJsonLength) {
        Objects.requireNonNull(json, "json");
        Objects.requireNonNull(schema, "schema");
        return CONVERTER.convertAll(json, schema, maxJsonLength);
    }

    // ---------------------------------------------------------------- JSON â†’ Avro bytes

    /**
     * Converts a single JSON document to an Avro Object Container File and returns the bytes.
     */
    public static byte[] toAvroBytes(String json, Schema schema) {
        return AvroIO.toBytes(schema, toRecord(json, schema));
    }

    /**
     * Converts a single JSON document to an Avro Object Container File and returns the bytes,
     * rejecting input longer than {@code maxJsonLength} characters.
     *
     * <p>This method provides a memory‑safety guard against accidentally
     * processing extremely large JSON strings that could exhaust heap memory.
     * The length check is performed before any parsing or tree construction.
     *
     * @param json JSON string to parse
     * @param schema Avro record schema
     * @param maxJsonLength maximum allowed length of the JSON string (in characters)
     * @return Avro bytes
     * @throws JsonConversionException if the JSON exceeds {@code maxJsonLength}
     * @since 1.0.0
     */
    public static byte[] toAvroBytes(String json, Schema schema, int maxJsonLength) {
        return AvroIO.toBytes(schema, toRecord(json, schema, maxJsonLength));
    }

    /**
     * Reads a JSON document from {@code in} and converts it to Avro bytes.
     * Closes the stream before returning.
     */
    public static byte[] toAvroBytes(InputStream in, Schema schema) {
        return AvroIO.toBytes(schema, toRecord(in, schema));
    }

    /**
     * Converts a JSON array (or single object) to an Avro Object Container File
     * containing all matching records, and returns the bytes.
     */
    public static byte[] toAvroBytesAll(String json, Schema schema) {
        return AvroIO.toBytes(schema, toRecords(json, schema));
    }

    /**
     * Converts a JSON array (or single object) to an Avro Object Container File
     * containing all matching records, and returns the bytes,
     * rejecting input longer than {@code maxJsonLength} characters.
     *
     * <p>This method provides a memory‑safety guard against accidentally
     * processing extremely large JSON strings that could exhaust heap memory.
     * The length check is performed before any parsing or tree construction.
     *
     * @param json JSON string to parse
     * @param schema Avro record schema
     * @param maxJsonLength maximum allowed length of the JSON string (in characters)
     * @return Avro bytes
     * @throws JsonConversionException if the JSON exceeds {@code maxJsonLength}
     * @since 1.0.0
     */
    public static byte[] toAvroBytesAll(String json, Schema schema, int maxJsonLength) {
        return AvroIO.toBytes(schema, toRecords(json, schema, maxJsonLength));
    }

    // ---------------------------------------------------------------- JSON â†’ Parquet bytes

    /**
     * Converts a single JSON document to Parquet bytes using the default codec (Snappy).
     */
    public static byte[] toParquetBytes(String json, Schema schema) {
        return ParquetIO.toBytes(schema, toRecord(json, schema));
    }

    /**
     * Converts a single JSON document to Parquet bytes using the default codec (Snappy),
     * rejecting input longer than {@code maxJsonLength} characters.
     *
     * <p>This method provides a memory‑safety guard against accidentally
     * processing extremely large JSON strings that could exhaust heap memory.
     * The length check is performed before any parsing or tree construction.
     *
     * @param json JSON string to parse
     * @param schema Avro record schema
     * @param maxJsonLength maximum allowed length of the JSON string (in characters)
     * @return Parquet bytes
     * @throws JsonConversionException if the JSON exceeds {@code maxJsonLength}
     * @since 1.0.0
     */
    public static byte[] toParquetBytes(String json, Schema schema, int maxJsonLength) {
        return ParquetIO.toBytes(schema, toRecord(json, schema, maxJsonLength));
    }

    /**
     * Reads a JSON document from {@code in} and converts it to Parquet bytes.
     * Closes the stream before returning.
     */
    public static byte[] toParquetBytes(InputStream in, Schema schema) {
        return ParquetIO.toBytes(schema, toRecord(in, schema));
    }

    /**
     * Converts a JSON array (or single object) to a Parquet file containing all
     * matching records, and returns the bytes.
     */
    public static byte[] toParquetBytesAll(String json, Schema schema) {
        return ParquetIO.toBytes(schema, toRecords(json, schema));
    }

    /**
     * Converts a JSON array (or single object) to a Parquet file containing all
     * matching records, and returns the bytes,
     * rejecting input longer than {@code maxJsonLength} characters.
     *
     * <p>This method provides a memory‑safety guard against accidentally
     * processing extremely large JSON strings that could exhaust heap memory.
     * The length check is performed before any parsing or tree construction.
     *
     * @param json JSON string to parse
     * @param schema Avro record schema
     * @param maxJsonLength maximum allowed length of the JSON string (in characters)
     * @return Parquet bytes
     * @throws JsonConversionException if the JSON exceeds {@code maxJsonLength}
     * @since 1.0.0
     */
    public static byte[] toParquetBytesAll(String json, Schema schema, int maxJsonLength) {
        return ParquetIO.toBytes(schema, toRecords(json, schema, maxJsonLength));
    }

    // ---------------------------------------------------------------- record → JSON

    /**
     * Converts a {@link GenericRecord} to a JSON string.
     *
     * <p>For flat schemas (carrying {@code pojoSchemaFlattened=true}), the flat fields
     * are reconstructed into a nested JSON document using each field's
     * {@code pojoSchemaFlattenSourcePath} property.
     */
    public static String fromRecord(GenericRecord record) {
        Objects.requireNonNull(record, "record");
        return TO_JSON.convert(record);
    }

    // ---------------------------------------------------------------- Avro bytes → JSON

    /**
     * Reads all records from Avro Object Container File bytes and converts each to a JSON string.
     *
     * <p>The Avro bytes must contain a single object container file (as produced by
     * {@link #toAvroBytes(String, Schema)} or {@link AvroIO#toBytes(Schema, GenericRecord)}).
     * Each record is converted using the shared {@link GenericRecordToJsonConverter}, which
     * respects flattened schemas (see {@link #fromRecord(GenericRecord)}).
     *
     * <p><b>Example:</b>
     * <pre>{@code
     * // Convert JSON to Avro bytes
     * byte[] avroBytes = JsonIO.toAvroBytes(json, schema);
     *
     * // Later, read back as JSON strings
     * List<String> jsonStrings = JsonIO.fromAvroBytes(avroBytes);
     * for (String json : jsonStrings) {
     *     System.out.println(json);
     * }
     * }</pre>
     *
     * @param avroBytes Avro Object Container File bytes; must not be {@code null}
     * @return a list of JSON strings, one per record in the container, in order
     * @throws io.github.jabhijeet.schema.io.AvroIOException if the bytes are not a valid Avro container
     * @see #fromParquetBytes(byte[])
     * @see AvroIO#readAll(byte[])
     */
    public static List<String> fromAvroBytes(byte[] avroBytes) {
        return AvroIO.readAll(avroBytes).stream().map(TO_JSON::convert).toList();
    }

    // ---------------------------------------------------------------- Parquet bytes → JSON

    /**
     * Reads all records from Parquet bytes and converts each to a JSON string.
     *
     * <p>The Parquet bytes must contain a single Parquet file (as produced by
     * {@link #toParquetBytes(String, Schema)} or {@link ParquetIO#toBytes(Schema, GenericRecord)}).
     * Each record is converted using the shared {@link GenericRecordToJsonConverter}, which
     * respects flattened schemas (see {@link #fromRecord(GenericRecord)}).
     *
     * <p><b>Note:</b> There is no separate {@code ParquetToJsonConverter} class because
     * Parquet files are read as Avro {@link GenericRecord} objects via {@link ParquetIO#readAll}.
     * The same {@link GenericRecordToJsonConverter} instance handles both Avro and Parquet records.
     *
     * <p><b>Example:</b>
     * <pre>{@code
     * // Convert JSON to Parquet bytes
     * byte[] parquetBytes = JsonIO.toParquetBytes(json, schema);
     *
     * // Later, read back as JSON strings
     * List<String> jsonStrings = JsonIO.fromParquetBytes(parquetBytes);
     * for (String json : jsonStrings) {
     *     System.out.println(json);
     * }
     * }</pre>
     *
     * @param parquetBytes Parquet file bytes; must not be {@code null}
     * @return a list of JSON strings, one per record in the file, in order
     * @throws io.github.jabhijeet.schema.io.ParquetIOException if the bytes are not a valid Parquet file
     * @see #fromAvroBytes(byte[])
     * @see ParquetIO#readAll(byte[])
     */
    public static List<String> fromParquetBytes(byte[] parquetBytes) {
        return ParquetIO.readAll(parquetBytes).stream().map(TO_JSON::convert).toList();
    }
}

